baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Three Point Photography'
theme = 'ananke'

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 10

[[menu.main]]
    name = "Products"
    url = "/products/"
    weight = 20

[[menu.main]]
    name = "Schedule"
    url = "/schedule/"
    weight = 30

[[menu.main]]
    name = "Payment"
    url = "/payment/"
    weight = 40
